### ISSUE TITLE
Adding new rows

### ISSUE THREAD

**Issue by Monishkumarvr** [nryabykh/streamlit-aggrid-hints#5]
Hi. Can you please help me in How can I add new empty rows to the grid after pressing button "Add row".

**Comment by nryabykh** [comment]
Hi! Please, check this article: https://towardsdatascience.com/automate-streamlit-web-app-using-interactive-aggrid-with-google-sheets-81b93fd9e648
It seems to contain all the clues you need.

**Comment by Monishkumarvr** [comment]
Thanks for sharing this. I implemented the code and it is working well.
